# Generated by Django 5.2.4 on 2025-07-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=90)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco_entrega', models.CharField(max_length=160)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=15)),
                ('nome_fornecedor', models.CharField(max_length=70)),
                ('razao_social', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=80)),
                ('data_admissão', models.DateField()),
                ('salario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=16)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
            ],
        ),
    ]
